// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {toast} from '../models';

export function Fetch(arg1:string):Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetDirectoryFiles(arg1:string):Promise<Array<string>>;

export function GetPath(arg1:string):Promise<string>;

export function MonitorFile(arg1:string):Promise<string>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:string):Promise<string>;

export function ReadJsonString(arg1:string):Promise<string>;

export function ShowNotification(arg1:string,arg2:string,arg3:Array<toast.Action>):Promise<string>;

export function WriteJsonString(arg1:string,arg2:string):Promise<void>;
