// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function GetDirectoryFiles(arg1) {
  return window['go']['main']['App']['GetDirectoryFiles'](arg1);
}

export function GetPath(arg1) {
  return window['go']['main']['App']['GetPath'](arg1);
}

export function MonitorFile(arg1) {
  return window['go']['main']['App']['MonitorFile'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function ReadJsonString(arg1) {
  return window['go']['main']['App']['ReadJsonString'](arg1);
}

export function ShowNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2, arg3);
}

export function WriteJsonString(arg1, arg2) {
  return window['go']['main']['App']['WriteJsonString'](arg1, arg2);
}
