// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectoryFiles(arg1) {
  return window['go']['main']['App']['GetDirectoryFiles'](arg1);
}

export function GetLines() {
  return window['go']['main']['App']['GetLines']();
}

export function GetPath(arg1) {
  return window['go']['main']['App']['GetPath'](arg1);
}

export function MonitorFile(arg1) {
  return window['go']['main']['App']['MonitorFile'](arg1);
}

export function ReadJsonString(arg1) {
  return window['go']['main']['App']['ReadJsonString'](arg1);
}

export function WriteJsonString(arg1, arg2) {
  return window['go']['main']['App']['WriteJsonString'](arg1, arg2);
}
