// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectoryFiles(arg1:string):Promise<Array<string>>;

export function GetLines():Promise<Array<string>>;

export function GetPath(arg1:string):Promise<string>;

export function MonitorFile(arg1:string):Promise<string>;

export function ReadJsonString(arg1:string):Promise<string>;

export function WriteJsonString(arg1:string,arg2:string):Promise<void>;
